### ISSUE TITLE
Update to 0.15

### ISSUE THREAD

**Issue by Alxandr** [eott/preciouspreciouscaffeine#4]
ShredGuy (https://www.twitch.tv/shredguy99) has stated that if this mod was update to 0.15 he would start a new map with it :P.

Regardless, should be updated to 0.15.

**Comment by eott** [comment]
The mod is now updated to 0.15 and also (hopefully) fixes a number of issues with multiplayer. Unfortunately it is now also incompatible with savegames that contain earlier versions.
